name: Scala CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [8, 11, 17, 21, 25]

    name: JDK ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Cache SBT
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2
            ~/.coursier
          key: ${{ matrix.os }}-${{matrix.java}}-sbt-${{ hashFiles('~/.sbt', '~/.ivy2', '~/.coursier') }}

      - name: Setup scala
        uses: sbt/setup-sbt@v1

      - name: Build
        run: sbt clean compile

      - name: Test
        run: sbt test