name: Github Actions Demo
run-name: GitHub actions by ${{ github.actor }}
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting GitHub action!"
      - run: echo "Running in ${{ runner.os }}"
      - run: echo "In branch ${{ github.ref }}"
      - name: Check out repo
        uses: actions/checkout@v5
      - name: List files
        run: |
          ls ${{ github.workspace }}